<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_filter</name>
   <tag></tag>
   <elementGuidId>ff5c2ec3-b587-4bf0-85f5-311c4b5c8ed1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.I4XfuLc53ubwVSBQcVb7M > button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/main/div/span[5]/div/div/div/div[2]/div[2]/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/ic_filter.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;aNWPbcduxteqYl7DfDJiY&quot;]/div[@class=&quot;container mx-auto&quot;]/span[5]/div[1]/div[1]/div[@class=&quot;w-full flex flex-wrap pb-1 pt-4&quot;]/div[@class=&quot;w-full md:w-3/6 lg:w-2/6 flex p-2&quot;]/div[@class=&quot;I4XfuLc53ubwVSBQcVb7M&quot;]/button[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/span[5]/div/div/div/div[2]/div[2]/button/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/img</value>
   </webElementXpaths>
</WebElementEntity>
