<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img___hapus file</name>
   <tag></tag>
   <elementGuidId>69abb8a6-03d1-4e4d-b6c4-560b9b162fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/main/div/div/div[2]/form/div[5]/div/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img._2zPu9Ysre6nS3g6yXS4kO5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2zPu9Ysre6nS3g6yXS4kO5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://minio-storage-core-tribe-edu-dev.vsan-apps.playcourt.id/web-assets/assets/ic_close.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;aNWPbcduxteqYl7DfDJiY&quot;]/div[@class=&quot;container mx-auto&quot;]/div[@class=&quot;h-full flex flex-col&quot;]/div[@class=&quot;LPpYLI-PAY0kHmHxRU2jN h-full mb-8 p-6 md:p-10&quot;]/form[1]/div[@class=&quot;md:ml-10&quot;]/div[@class=&quot;_2B54RAR84FyaJVN-MDIu4M&quot;]/div[@class=&quot;_1pvwe5jOU44fMsuWvgsUgm&quot;]/div[@class=&quot;BQYI-3MmBVxNa2s3OgPvz w-full&quot;]/div[@class=&quot;border-dashed border-2 p-4 border-gray-500&quot;]/div[@class=&quot;flex justify-center p-10&quot;]/div[@class=&quot;p-4 border-2 relative max-w-full&quot;]/img[@class=&quot;_2zPu9Ysre6nS3g6yXS4kO5&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/div[2]/form/div[5]/div/div[2]/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://minio-storage-core-tribe-edu-dev.vsan-apps.playcourt.id/web-assets/assets/ic_close.svg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
